# Site settings
title: Análise de Dados 2
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Resultados dos laboratórios da disciplina.
baseurl: "/AD2" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  michellymenezes
permalink: /:year/:month/:title.html

# Build settings
markdown: kramdown
